### ISSUE TITLE
doc: getting started?

### ISSUE THREAD

**Issue by monperrus** [jsa-aerial/DMM#1]
How to compile DMM? How to execute a first DMM program?

**Comment by anhinga** [comment]
The easiest starting point is to execute one of the Quil-controlled examples.

E.g. clone the project, open https://github.com/jsa-aerial/DMM/blob/master/examples/dmm/quil-controlled/jul_13_2017_experiment.clj in, for example, CIDER of Emacs (or any other Clojure environment), open REPL, and load the code buffer - you'll have a small DMM running in a graphical window which accumulates and renders the list of mouse clicks.

**Comment by anhinga** [comment]
I also created and committed https://github.com/jsa-aerial/DMM/blob/master/doc/README.md file with these instructions.

**Comment by anhinga** [comment]
(And added instructions for people who are not currently running Clojure on their machines, but still would like to try.)

**Comment by monperrus** [comment]
Thanks. I make progress, see #3

**Comment by Kinrany** [comment]
You might want to link those instructions in the root folder README, it's not very obvious that the papers mentioned in it are not the only docs available

**Comment by anhinga** [comment]
Done, thanks!
